services:
  - type: web
    name: variant-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0


